[package]
name        = "hkd32"
description = """
              HMAC-based Hierarchical Key Derivation: deterministically derive
              a hierarchy of symmetric keys from initial keying material through
              repeated applications of the Hash-based Message Authentication Code
              (HMAC) construction.
              """
version     = "0.1.1" # Also update html_root_url in lib.rs when bumping this
authors     = ["Tony Arcieri <tony@iqlusion.io>"]
license     = "Apache-2.0"
edition     = "2018"
homepage    = "https://github.com/iqlusioninc/crates/"
repository  = "https://github.com/iqlusioninc/crates/tree/develop/hkd32"
readme      = "README.md"
categories  = ["cryptography", "no-std"]
keywords    = ["bip32", "derivation", "hd", "hmac", "key"]

[badges]
maintenance = { status = "passively-maintained" }
travis-ci = { repository = "iqlusioninc/crates", branch = "develop" }

[dependencies]
getrandom = { version = "0.1", optional = true }
hmac = { version = "0.7", default-features = false }
sha2 = { version = "0.8", default-features = false }
subtle-encoding = { version = "0.3", optional = true }
tiny-bip39 = { version = "0.6", default-features = false, optional = true }

[dependencies.zeroize]
version = "0.9"
path = "../zeroize"
default-features = false
features = ["zeroize_derive"]

[features]
default = ["alloc", "bech32", "getrandom"]
alloc = ["zeroize/alloc"]
bech32 = ["alloc", "subtle-encoding/bech32-preview"]
mnemonic = ["alloc", "tiny-bip39"]

[package.metadata.docs.rs]
all-features = true
