[package]
name        = "tai64"
description = "TAI64 and TAI64N (i.e. Temps Atomique International) timestamp support for Rust"
version     = "1.0.0" # Also update html_root_url in lib.rs when bumping this
authors     = ["Tony Arcieri <tony@iqlusion.io>", "sopium <sopium@mysterious.site>"]
license     = "Apache-2.0"
homepage    = "https://github.com/iqlusioninc/crates/"
repository  = "https://github.com/iqlusioninc/crates/tree/master/tai64"
readme      = "README.md"
categories  = ["date-and-time", "internationalization", "network-programming", "parser-implementations"]
keywords    = ["tai64", "time", "timestamps", "chrono"]

[badges]
circle-ci = { repository = "iqlusioninc/crates" }

[dependencies]
byteorder = "1.0"
chrono = { version = "0.4", optional = true, default-features = false }

[features]
default = []

[dev-dependencies]
quickcheck = "0.6"

[package.metadata.docs.rs]
features = ["chrono"]
