language: rust
cache: cargo

branches:
  only:
    - develop

rust:
  - 1.35.0 # Minimum supported
  - stable # Stable should always be supported

os:
  - linux
  - osx
  - windows

matrix:
  fast_finish: true
  allow_failures:
    # We still rely on Appveyor for Windows testing since it's more
    # reliable and performs better, but this lets us keep an eye on
    # improvements to Travis Windows support
    - os: windows
  include:
    - name: "Rust: stable (wasm32)"
      rust: stable
      script:
      - cargo build --package secrecy --target wasm32-unknown-unknown
      - cargo build --package subtle-encoding --target wasm32-unknown-unknown
      - cargo build --package tai64 --target wasm32-unknown-unknown
      - cargo build --package zeroize --target wasm32-unknown-unknown

install:
  - rustup component add rustfmt
  - rustup component add clippy
  - rustup target add wasm32-unknown-unknown
  - command -v cargo-audit >/dev/null 2>&1 || cargo install cargo-audit

script:
  # audit
  - cargo audit

  # lint
  - cargo fmt --version
  - cargo fmt --all -- --check
  - cargo clippy --version
  - cargo clippy --all

  # test without default features
  - cargo test --all --no-default-features --release

  # test with default features
  - cargo test --all --release

  # test with all features
  - cargo test --all --all-features --release

  # doc build
  - cargo doc --no-deps
