language: rust
cache: cargo

branches:
  only:
    - develop

rust:
  - 1.36.0 # Minimum supported
  - stable # Stable should always work too

os: linux

env:
  - RUSTFLAGS="-D warnings"

matrix:
  fast_finish: true
  allow_failures:
    # We still rely on Appveyor for Windows testing since it's more
    # reliable and performs better, but this lets us keep an eye on
    # improvements to Travis Windows support
    - os: windows
  include:
    # Travis hasn't bumped `stable` on macOS to 1.36 yet =(
    - name: "Rust: 1.36"
      os: osx
      rust: 1.36.0
    - name: "Rust: 1.36"
      os: windows
      rust: 1.36.0
    - name: audit
      rust: stable
      install:
        - command -v cargo-audit >/dev/null 2>&1 || cargo install cargo-audit
      script:
        - cargo audit
    - name: rustfmt
      rust: stable
      install:
        - rustup component add rustfmt
      script:
        - cargo fmt --version
        - cargo fmt --all -- --check
    - name: clippy
      rust: stable
      install:
        - rustup component add clippy
      script:
        - cargo clippy --version
        - cargo clippy --all
    - name: "Rust: stable (wasm32)"
      install:
        - rustup target add wasm32-unknown-unknown
      rust: stable
      script:
      - cargo build --all --exclude canonical-path,gaunt --target wasm32-unknown-unknown

script:
  # test without default features
  - cargo test --all --no-default-features --release

  # test with default features
  - cargo test --all --release

  # test with all features
  - cargo test --all --all-features --release

  # doc build
  - cargo doc --no-deps
