[workspace]
members = [
    "canonical-path",
    "gaunt",
    "subtle-encoding",
    "tai64",
    "tendermint-rpc",
    "zeroize",
    "zeroize_derive"
]

# Enable integer overflow checks in release builds
# WARNING: DO NOT REMOVE THIS! We rely on this for panic-on-overflow semantics
# in the event of integer arithmetic bugs.
[profile.release]
overflow-checks = true

[patch.crates-io]
tendermint = { git = "https://github.com/tendermint/kms", rev = "tendermint-rs/updates-and-cleanups" }
