[workspace]
members = [
    "canonical-path",
    "gaunt",
    "subtle-encoding",
    "tai64",
    "zeroize"
]

# Enable integer overflow checks in release builds
# WARNING: DO NOT REMOVE THIS! We rely on this for abort-on-overflow semantics
# in the event of integer arithmetic bugs.
[profile.release]
overflow-checks = true
