[package]
name        = "iq-cli"
description = "Cargo-like colored command-line interfaces"
version     = "0.0.0" # Also update html_root_url in lib.rs when bumping this
authors     = ["Tony Arcieri <tony@iqlusion.io>"]
homepage    = "https://github.com/iqlusion-io/crates/"
repository  = "https://github.com/iqlusion-io/crates/tree/master/iq-cli"
readme      = "README.md"
categories  = ["command-line-interface"]
keywords    = ["cli", "color"]

[badges]
circle-ci = { repository = "iqlusion-io/crates" }

[dependencies]
lazy_static = "1"
libc = "0.2"
term = "0.5"
