version: 2

jobs:
  build:
    docker:
      - image: iqlusion/rust-ci:201804060 # bump cache keys when modifying this
    environment:
      - PROJECTS=tai64

    steps:
      - checkout
      - restore_cache:
          key: cache-201804060 # bump save_cache key below too
      - run:
          name: rustfmt
          command: |
            rustfmt --version
            for project in $PROJECTS; do
              echo "project: $project"
              (cd $project && cargo fmt -- --write-mode=diff)
            done
      - run:
          name: clippy
          command: |
            cargo clippy --version
            for project in $PROJECTS; do
              echo "project: $project"
              (cd $project && rustup run $RUST_NIGHTLY_VERSION cargo clippy)
            done
      - run:
          name: tai64
          command: |
            rustc --version
            cargo --version
            cd tai64
            cargo build
            cargo test
            cargo test --features=chrono
      - save_cache:
          key: cache-201804060 # bump restore_cache key above too
          paths:
            - "~/.cargo"
            - "./target"
