[package]
name        = "secrecy"
description = """
              Wrapper types and traits for secret management which help ensure
              they aren't accidentally copied, logged, or otherwise exposed
              (as much as possible), and also ensure secrets are securely wiped
              from memory when dropped.
              """
version     = "0.3.1" # Also update html_root_url in lib.rs when bumping this
authors     = ["Tony Arcieri <tony@iqlusion.io>"]
license     = "Apache-2.0 OR MIT"
edition     = "2018"
homepage    = "https://github.com/iqlusioninc/crates/"
repository  = "https://github.com/iqlusioninc/crates/tree/develop/secrecy"
readme      = "README.md"
categories  = ["cryptography", "memory-management", "no-std", "os"]
keywords    = ["clear", "memory", "secret", "secure", "wipe"]

[badges]
maintenance = { status = "passively-maintained" }
travis-ci = { repository = "iqlusioninc/crates", branch = "develop" }

[dependencies]
serde = { version = "1", optional = true, features = ["derive"] }
zeroize = { version = "0.10", path = "../zeroize", default-features = false }
bytes_crate = { package = "bytes", version = "0.4", features = ["serde"], optional = true }

[features]
default = ["alloc"]
alloc = ["zeroize/alloc"]
bytes = ["bytes_crate", "zeroize/bytes"]
