[package]
name        = "subtle-encoding"
description = """
              Encoders and decoders for common data encodings (i.e. hex, identity)
              which avoid data-dependent branching/table lookups and therefore
              "best effort" constant time. Useful for encoding/decoding secret
              values such as cryptographic keys.
              """
version     = "0.0.0" # Also update html_root_url in lib.rs when bumping this
authors     = ["Tony Arcieri <tony@iqlusion.io>"]
license     = "Apache-2.0 OR MIT"
homepage    = "https://github.com/iqlusioninc/crates/"
repository  = "https://github.com/iqlusioninc/crates/tree/master/subtle-encoding"
readme      = "README.md"
categories  = ["cryptography", "encoding", "no-std"]
keywords    = ["constant-time", "hex", "keys", "secrets", "security"]

[dependencies]
failure = "0.1"
failure_derive = "0.1"

[features]
default = ["hex", "std"]
alloc = []
hex = []
std = ["alloc"]

[badges]
circle-ci = { repository = "iqlusioninc/crates" }
